version: '3.2'


services:

 app1:
   build:
     context: app/
   container_name:
     "app1"
   hostname:
      "app1.host"
   expose:
     - "5000"

 app2:
   build:
     context: app/
   container_name:
     "app2"
   hostname:
     "app2.host"
   expose:
     - "5000"

 loadbalancer:
   build:
     context: lb/
   container_name:
     "loadbalancer"
   hostname:
     "loadbalancer.host"
   ports: 
     - "80:80"
   links: 
     - app1
     - app2
